"""
Initialize Pattern Matching Module.
"""
from mlfinlab.online_portfolio_selection.pattern_matching.correlation_driven_nonparametric_learning import CORN
from mlfinlab.online_portfolio_selection.pattern_matching.correlation_driven_nonparametric_learning_uniform import CORNU
from mlfinlab.online_portfolio_selection.pattern_matching.correlation_driven_nonparametric_learning_k import CORNK
from mlfinlab.online_portfolio_selection.pattern_matching.symmetric_correlation_driven_nonparametric_learning import SCORN
from mlfinlab.online_portfolio_selection.pattern_matching.symmetric_correlation_driven_nonparametric_learning_k import SCORNK
from mlfinlab.online_portfolio_selection.pattern_matching.functional_correlation_driven_nonparametric_learning import FCORN
from mlfinlab.online_portfolio_selection.pattern_matching.functional_correlation_driven_nonparametric_learning_k import FCORNK
