"""
Initialize Mean Reversion Module.
"""
from mlfinlab.online_portfolio_selection.mean_reversion.robust_median_reversion import RobustMedianReversion
from mlfinlab.online_portfolio_selection.mean_reversion.passive_aggressive_mean_reversion import PassiveAggressiveMeanReversion
from mlfinlab.online_portfolio_selection.mean_reversion.confidence_weighted_mean_reversion import ConfidenceWeightedMeanReversion
from mlfinlab.online_portfolio_selection.mean_reversion.online_moving_average_reversion import OnlineMovingAverageReversion
