"""
Initialize Online Portfolio Selection Module.
"""
# Parent Class
from mlfinlab.online_portfolio_selection.online_portfolio_selection import OLPS
from mlfinlab.online_portfolio_selection.universal_portfolio import UniversalPortfolio

# Benchmarks
from mlfinlab.online_portfolio_selection.benchmarks.buy_and_hold import BuyAndHold
from mlfinlab.online_portfolio_selection.benchmarks.best_stock import BestStock
from mlfinlab.online_portfolio_selection.benchmarks.constant_rebalanced_portfolio import ConstantRebalancedPortfolio
from mlfinlab.online_portfolio_selection.benchmarks.best_constant_rebalanced_portfolio import BestConstantRebalancedPortfolio

# Momentum
from mlfinlab.online_portfolio_selection.momentum.exponential_gradient import ExponentialGradient
from mlfinlab.online_portfolio_selection.momentum.follow_the_leader import FollowTheLeader
from mlfinlab.online_portfolio_selection.momentum.follow_the_regularized_leader import FollowTheRegularizedLeader

# Mean Reversion
from mlfinlab.online_portfolio_selection.mean_reversion.robust_median_reversion import RobustMedianReversion
from mlfinlab.online_portfolio_selection.mean_reversion.passive_aggressive_mean_reversion import PassiveAggressiveMeanReversion
from mlfinlab.online_portfolio_selection.mean_reversion.confidence_weighted_mean_reversion import ConfidenceWeightedMeanReversion
from mlfinlab.online_portfolio_selection.mean_reversion.online_moving_average_reversion import OnlineMovingAverageReversion

# Pattern Matching
from mlfinlab.online_portfolio_selection.pattern_matching.correlation_driven_nonparametric_learning import CorrelationDrivenNonparametricLearning
from mlfinlab.online_portfolio_selection.pattern_matching.correlation_driven_nonparametric_learning_uniform import CorrelationDrivenNonparametricLearningUniform
from mlfinlab.online_portfolio_selection.pattern_matching.correlation_driven_nonparametric_learning_k import CorrelationDrivenNonparametricLearningK
from mlfinlab.online_portfolio_selection.pattern_matching.symmetric_correlation_driven_nonparametric_learning import SymmetricCorrelationDrivenNonparametricLearning
from mlfinlab.online_portfolio_selection.pattern_matching.symmetric_correlation_driven_nonparametric_learning_k import SymmetricCorrelationDrivenNonparametricLearningK
from mlfinlab.online_portfolio_selection.pattern_matching.functional_correlation_driven_nonparametric_learning import FunctionalCorrelationDrivenNonparametricLearning
from mlfinlab.online_portfolio_selection.pattern_matching.functional_correlation_driven_nonparametric_learning_k import FunctionalCorrelationDrivenNonparametricLearningK
