#!/bin/bash

# Note: To run specific modules for code coverage, run this command, e.g.:
#   coverage run -m unittest mlfinlab.tests.unit.test_mod1 mlfinlab.tests.unit.test_mod2

# Remove multiprocessing coverage files in case a previous combine wasn't performed
rm .coverage.*
rm -fR cover/
# Remove the main coverage file (.coverage)
coverage erase
# Discover and run all tests
coverage run --concurrency=multiprocessing ./scripts/run_tests.py discover -v
coverage combine
coverage report
