"""
Initialize Momentum Module.
"""
from mlfinlab.online_portfolio_selection.momentum.exponential_gradient import ExponentialGradient
from mlfinlab.online_portfolio_selection.momentum.follow_the_leader import FollowTheLeader
from mlfinlab.online_portfolio_selection.momentum.follow_the_regularized_leader import FollowTheRegularizedLeader
